export {
  DESKTOP_PROTOCOL_MIN_VERSION,
  DESKTOP_PROTOCOL_VERSION,
  createDesktopCommand,
  createHostMessage,
} from "./envelope.js";
export { decodeDesktopToHostMessage } from "./validation.js";
export type {
  DesktopCommandMetadata,
  HostMessageMetadata,
  ProtocolFeature,
  ProtocolHello,
} from "./envelope.js";
export type { ProtocolDecodeResult } from "./validation.js";
export type {
  AgentHostLaunch,
  AgentHostLifecycle,
  AgentHostLog,
  AutomaticUpdateReport,
  DesktopBootstrap,
  DesktopHostState,
  DesktopHostStatus,
  DesktopShellSnapshot,
  DesktopShellStatus,
  DesktopTaskState,
  DesktopTaskStatus,
  DesktopToHostPayload,
  DesktopToHostMessage,
  EndpointDiscoveryDraft,
  EndpointDraft,
  EndpointKind,
  EndpointProfile,
  EndpointRuntimeConfig,
  EndpointTestResult,
  ExtensionDraft,
  ExtensionFinding,
  ExtensionFindingSeverity,
  ExtensionIntegrityMode,
  ExtensionProfile,
  ExtensionRuntimeConfig,
  ExtensionScanResult,
  ExtensionSourceKind,
  ExtensionUpdate,
  ExtensionVersion,
  HostToDesktopMessage,
  HostToDesktopPayload,
  PiSessionEvent,
  PiAgentUpdateStatus,
  ProjectSummary,
  PersistedTask,
  PersistedTaskDraft,
  PersistedTaskEvent,
  PersistedTaskSnapshot,
  MarketplacePackage,
  MarketplacePage,
  MarketplaceSort,
  RepositoryInfo,
  TaskEventReplay,
  TaskCreateDraft,
  TaskAttachment,
  TaskAttachmentKind,
  TaskIsolation,
  TaskBrokerRequest,
  TaskPermissionMode,
  TaskPermissionRequest,
  TaskPromptAttachment,
  TaskRuntimeProfile,
  TaskTranscriptMessage,
  TaskWorktree,
  TerminalExit,
  TerminalLaunch,
  TerminalOutput,
  UpdatePreferences,
  WorkspaceChange,
  WorkspaceChangeStatus,
  WorkspaceDiff,
  WorkspaceFileContent,
  WorkspaceFileEntry,
  WorkspaceHunkOperation,
  WorkspaceHunkRef,
  WorkspacePatchResult,
  WorkspaceSnapshot,
  WorktreeInfo,
} from "./messages.js";
